--
-- PostgreSQL database dump
--

\restrict rFe5gcO5GxxUxLqGQeV6KLZ1Fr0SjBsxr7Bs9bfdhwQ1yTcxe1DhRijA667NQSj

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    address character varying(255),
    created_at timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true
);


ALTER TABLE public.app_users OWNER TO postgres;

--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    name character varying(255),
    email character varying(255),
    address character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: app_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_users (id, name, email, password_hash, address, created_at, is_active) FROM stdin;
1	Admin User	admin@example.com	$2a$11$KIXxPZvJ8qYqJZqJZqJZqO8qYqJZqJZqJZqJZqJZqJZqJZqJZqJZq	Main Office	2026-03-05 16:01:48.89234+05	t
2	superuser	su@gmail.com	$2a$11$ORrt/tt9vGAh/Zk7s2lkmeumvMSuzt1XGWrpStPNATvqHak9QFFqi	FineCity	2026-03-05 16:01:48.89234+05	t
3	Эрик Кочетов	erickoch1@mail.ru	$2a$11$FsaHozKAPlb3eGD5UHGIN.aAvSYIdZ0MlQas.bu/uWKkPOwfvtoZ.	г. Пермь	2026-03-05 16:52:32.098465+05	t
4	Жека Андреев	evgen.gainy@gmail.com	$2a$11$rDh7e9RE7HYh5rdfpTyyKO/NPcfan5xPOG2gviiXuVaAAnFHxgyrC	г. Пермь	2026-03-05 16:56:21.587226+05	t
5	kik67	izirep@mail.ru	$2a$11$zl2y74S.PDp9V9wx0l70zO.QeZR13eF1M8Da/RKlwU155BTiGLSEG	г. Гайны	2026-03-05 17:00:07.317321+05	t
6	вап	dsfs@mail.ru	$2a$11$sOvMU/.T2dFIiTDlOoklkedJ7akD1LbKqtgqf.1fHmGd/tdYit3Zu	345	2026-03-05 19:48:02.602099+05	t
7	сеня лохов	kfhkfhkd@mail.ru	$2a$11$nsw7Om13TgkPLivRsUjIyexXeKBWWJ1NTo/VyL/mUe35/u7KVSpMu	г. Пермь	2026-03-05 22:15:52.534756+05	t
8	sfgdsfg	jopa@mail.ru	$2a$11$uEtsCUgBMFgtR7EWEOhOkOR.Xv3kTaOIwObWyOPXzbiVNS44.wG6a	г. Пермь	2026-04-07 17:17:04.848553+05	t
9	ips ips	pisya@mail.ru	$2a$11$08L/eASXVdR3tYioz.82De7gs/AGt4fC1ouOtQkjb4uxXbjdem4A6	г. Гайны	2026-04-07 17:19:27.293885+05	t
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, name, email, address) FROM stdin;
6	Kate	kate@gmail.com	FineCity
1	Tom	tom@gmail.com	ИЖЕВСК
7	Ишак	неважно	Москва
3	John Sinaa	john@gmail.com	FineCity
5	Pupkin хех	pupkin@gmail.com	FarCity
\.


--
-- Name: app_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_users_id_seq', 9, true);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 7, true);


--
-- Name: app_users app_users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_email_key UNIQUE (email);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict rFe5gcO5GxxUxLqGQeV6KLZ1Fr0SjBsxr7Bs9bfdhwQ1yTcxe1DhRijA667NQSj

